In [ ]:
import numpy as np
import pandas as pd

# 1. Create and display the dataset
data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany',
                'France', 'Spain', 'France', np.nan, 'France'],
    'Age': [44.0, 27.0, 30.0, 38.0, 40.0, 35.0, np.nan, 48.0, 50.0, 37.0],
    'Salary': [72000.0, 48000.0, 54000.0, 61000.0, np.nan,
               58000.0, 52000.0, 79000.0, 83000.0, 67000.0],
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes',
                  'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

print("OUTPUT 1: ORIGINAL DATASET")
display(df)

# 2. Display dataset information
print("OUTPUT 2: DATASET INFORMATION")
df.info()

# 3. Display Country column
print("\nOUTPUT 3: COUNTRY COLUMN")
display(df[['Country']])

# 4. Find the mode of Country
print("OUTPUT 4: MODE OF COUNTRY")
display(df.Country.mode())

# 5. Display the first mode value
print("OUTPUT 5: FIRST MODE VALUE")
print(df.Country.mode()[0])

# 6. Display the type of mode
print("OUTPUT 6: TYPE OF MODE")
print(type(df.Country.mode()))

# 7. Handle missing values and display the cleaned dataset
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Salary'] = df['Salary'].fillna(round(df['Salary'].mean()))

print("OUTPUT 7: DATASET AFTER HANDLING MISSING VALUES")
display(df)

# 8. Display one-hot encoded Country columns
print("OUTPUT 8: ONE-HOT ENCODING")
display(pd.get_dummies(df.Country))

# Create the updated dataset
updated_dataset = pd.concat(
    [pd.get_dummies(df.Country), df.iloc[:, [1, 2, 3]]],
    axis=1
)

print("UPDATED DATASET AFTER COUNTRY ENCODING")
display(updated_dataset)

# Display the cleaned dataframe information
print("DATAFRAME INFORMATION AFTER CLEANING")
df.info()

# Convert Purchased: No = 0 and Yes = 1
updated_dataset['Purchased'] = updated_dataset['Purchased'].replace(
    {'No': 0, 'Yes': 1}
)

print("FINAL UPDATED DATASET")
display(updated_dataset)

print("EXPERIMENT NO. 15 COMPLETED SUCCESSFULLY")

OUTPUT 1: ORIGINAL DATASET

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8      NaN  50.0  83000.0        No
9   France  37.0  67000.0       Yes

OUTPUT 2: DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

OUTPUT 3: COUNTRY COLUMN

   Country
0   France
1    Spain
2  Germany
3    Spain
4  Germany
5   France
6    Spain
7   France
8      NaN
9   France

OUTPUT 4: MODE OF COUNTRY

0    France
Name: Country, dtype: object

OUTPUT 5: FIRST MODE VALUE
France
OUTPUT 6: TYPE OF MODE
<class 'pandas.core.series.Series'>
OUTPUT 7: DATASET AFTER HANDLING MISSING VALUES

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

OUTPUT 8: ONE-HOT ENCODING

   France  Germany  Spain
0    True    False  False
1   False    False   True
2   False     True  False
3   False    False   True
4   False     True  False
5    True    False  False
6   False    False   True
7    True    False  False
8    True    False  False
9    True    False  False

UPDATED DATASET AFTER COUNTRY ENCODING

   France  Germany  Spain   Age   Salary Purchased
0    True    False  False  44.0  72000.0        No
1   False    False   True  27.0  48000.0       Yes
2   False     True  False  30.0  54000.0        No
3   False    False   True  38.0  61000.0        No
4   False     True  False  40.0  63778.0       Yes
5    True    False  False  35.0  58000.0       Yes
6   False    False   True  38.0  52000.0        No
7    True    False  False  48.0  79000.0       Yes
8    True    False  False  50.0  83000.0        No
9    True    False  False  37.0  67000.0       Yes

DATAFRAME INFORMATION AFTER CLEANING
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes
FINAL UPDATED DATASET

/tmp/ipykernel_2398/2442115530.py:66: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  updated_dataset['Purchased'] = updated_dataset['Purchased'].replace(

   France  Germany  Spain   Age   Salary  Purchased
0    True    False  False  44.0  72000.0          0
1   False    False   True  27.0  48000.0          1
2   False     True  False  30.0  54000.0          0
3   False    False   True  38.0  61000.0          0
4   False     True  False  40.0  63778.0          1
5    True    False  False  35.0  58000.0          1
6   False    False   True  38.0  52000.0          0
7    True    False  False  48.0  79000.0          1
8    True    False  False  50.0  83000.0          0
9    True    False  False  37.0  67000.0          1

EXPERIMENT NO. 15 COMPLETED SUCCESSFULLY